<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas

In [1]:
import pandas as pd
import numpy as np

In [3]:
data=np.array(['g','e','e','k','s','f','o','r','g','e','k','s'])
ser=pd.Series(data)
print(ser)

0     g
1     e
2     e
3     k
4     s
5     f
6     o
7     r
8     g
9     e
10    k
11    s
dtype: object

In [4]:
data=np.array(['g','e','e','k','s','f','o','r','g','e','k','s'])
ser=pd.Series(data)
print(ser[:5])

0    g
1    e
2    e
3    k
4    s
dtype: object

In [5]:
data=np.array(['g','e','e','k','s','f','o','r','g','e','k','s'])
ser=pd.Series(data)
print(ser[5:])

5     f
6     o
7     r
8     g
9     e
10    k
11    s
dtype: object

Binary Operation on Series

In [6]:
data=pd.Series([5,2,3,7],index=['a','b','c','d'])
data1=pd.Series([1,6,4,9],index=['a','b','d','e'])
print(data,data1)

a    5
b    2
c    3
d    7
dtype: int64 a    1
b    6
d    4
e    9
dtype: int64

In [7]:
data.add(data1,fill_value=0)

a     6.0
b     8.0
c     3.0
d    11.0
e     9.0
dtype: float64

In [8]:
data.sub(data1,fill_value=0)

a    4.0
b   -4.0
c    3.0
d    3.0
e   -9.0
dtype: float64

In [9]:
data.mul(data1,fill_value=0)

a     5.0
b    12.0
c     0.0
d    28.0
e     0.0
dtype: float64

In [10]:
data.div(data1,fill_value=0)

a    5.000000
b    0.333333
c         inf
d    1.750000
e    0.000000
dtype: float64

In [14]:
data.pow(data1,fill_value=0)
#exponential power

a       5.0
b      64.0
c       1.0
d    2401.0
e       0.0
dtype: float64

In [15]:
data.mod(data1,fill_value=0)

a    0.0
b    2.0
c    NaN
d    3.0
e    0.0
dtype: float64

In [19]:
companies=['Google','Microsoft','Facebook','Apple']
pd.Series(companies)

0       Google
1    Microsoft
2     Facebook
3        Apple
dtype: object

In [20]:
pd.Series(companies,index=[100,101,102,103])

100       Google
101    Microsoft
102     Facebook
103        Apple
dtype: object

In [21]:
pd.Series(companies,index=['GOOGLE','MSFT','FB','APPLE'])

GOOGLE       Google
MSFT      Microsoft
FB         Facebook
APPLE         Apple
dtype: object

In [23]:
companies={'GOOGLE':0,'MSFT':1,'FB':2,'APPLE':3}
pd.Series(companies)

GOOGLE    0
MSFT      1
FB        2
APPLE     3
dtype: int64

In [25]:
companies={
    'a':'GOOGLE',
    'b':'MSFT',
    'c':'FB',
    'd':'APPLE'
}
pd.Series(companies)

a    GOOGLE
b      MSFT
c        FB
d     APPLE
dtype: object

In [26]:
pd.Series(5,index=[100,101,102,103])

100    5
101    5
102    5
103    5
dtype: int64

In [32]:
data2=[{"a":1,"b":2},{"a":5,"b":10,"c":20}]
pd.DataFrame(data2)

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [33]:
pd.DataFrame(data2,index=['first','second'])

        a   b     c
first   1   2   NaN
second  5  10  20.0

In [34]:
pd.DataFrame(data2,columns=['a','b'])

   a   b
0  1   2
1  5  10

In [35]:
pd.DataFrame(data2,index=['first','second'],columns=['a','b'])

        a   b
first   1   2
second  5  10

Joins

In [37]:
df1=pd.DataFrame({'lkey':['foo','bar','baz','foo'],'value':[1,2,3,5]})
df2=pd.DataFrame({'rkey':['foo','bar','baz','foo'],'value':[5,6,7,8]})
df1.join(df2,lsuffix='_l',rsuffix='_r')

  lkey  value_l rkey  value_r
0  foo        1  foo        5
1  bar        2  bar        6
2  baz        3  baz        7
3  foo        5  foo        8

In [38]:
df1=pd.DataFrame({'key':['K0','K1','K5','K3','K4','K2'],
                  'A':['A0','A1','A2','A3','A4','A5']})
df2=pd.DataFrame({'key':['K0','K1','K2'],
                  'B':['B0','B1','B2']})

In [39]:
df1.join(df2,lsuffix='_l',rsuffix='_r')

  key_l   A key_r    B
0    K0  A0    K0   B0
1    K1  A1    K1   B1
2    K5  A2    K2   B2
3    K3  A3   NaN  NaN
4    K4  A4   NaN  NaN
5    K2  A5   NaN  NaN

In [40]:
df1=pd.DataFrame({'key':['K0','K1','K5','K3','K4','K2'],
                  'A':['A0','A1','A2','A3','A4','A5']},
                 index=[0,1,2,3,4,5])
df2=pd.DataFrame({'key':['K0','K1','K2'],
                  'B':['B0','B1','B2']},
                 index=[0,1,2])
df1.join(df2,lsuffix='_l',rsuffix='_r')

  key_l   A key_r    B
0    K0  A0    K0   B0
1    K1  A1    K1   B1
2    K5  A2    K2   B2
3    K3  A3   NaN  NaN
4    K4  A4   NaN  NaN
5    K2  A5   NaN  NaN

In [41]:
#inner join
df1.join(df2,lsuffix='_l',rsuffix='_r',how='inner')

  key_l   A key_r   B
0    K0  A0    K0  B0
1    K1  A1    K1  B1
2    K5  A2    K2  B2

In [42]:
#outer join
df1.join(df2,lsuffix='_l',rsuffix='_r',how='outer')

  key_l   A key_r    B
0    K0  A0    K0   B0
1    K1  A1    K1   B1
2    K5  A2    K2   B2
3    K3  A3   NaN  NaN
4    K4  A4   NaN  NaN
5    K2  A5   NaN  NaN

In [46]:
#join on column
df1.set_index('key').join(df2.set_index('key'))

      A    B
key
K0   A0   B0
K1   A1   B1
K5   A2  NaN
K3   A3  NaN
K4   A4  NaN
K2   A5   B2

Concat

In [47]:
m1=pd.Series(['m','n'])
m2=pd.Series(['p','q'])
pd.concat([m1,m2])

0    m
1    n
0    p
1    q
dtype: object

In [49]:
m1=pd.DataFrame({
    'Name':['Alex','Amy','Allen','Alice','Ayoung'],
    'subject_id':['sub1','sub2','sub4','sub6','sub5'],
    'Marks_scored':[98,90,87,69,78]},
                index=[1,2,3,4,5])
m2=pd.DataFrame({
    'Name':['Billy','Brian','Bran','Bryce','Betty'],
    'subject_id':['sub2','sub4','sub3','sub6','sub5'],
    'Marks_scored':[89,80,79,97,88]},
                index=[1,2,3,4,5])
pd.concat([m1,m2])

     Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78
1   Billy       sub2            89
2   Brian       sub4            80
3    Bran       sub3            79
4   Bryce       sub6            97
5   Betty       sub5            88

In [51]:
pd.concat([m1,m2],axis=1)

     Name subject_id  Marks_scored   Name subject_id  Marks_scored
1    Alex       sub1            98  Billy       sub2            89
2     Amy       sub2            90  Brian       sub4            80
3   Allen       sub4            87   Bran       sub3            79
4   Alice       sub6            69  Bryce       sub6            97
5  Ayoung       sub5            78  Betty       sub5            88

In [52]:
df1=pd.DataFrame({'A':[1,2,3],'B':[1,2,3]})
df2=pd.DataFrame({'A':[4,5,6],'B':[4,5,6]})
pd.concat([df1,df2])

   A  B
0  1  1
1  2  2
2  3  3
0  4  4
1  5  5
2  6  6

In [53]:
df=pd.concat([df1,df2],keys=['x','y'])
df

     A  B
x 0  1  1
  1  2  2
  2  3  3
y 0  4  4
  1  5  5
  2  6  6

In [60]:
df=pd.concat([df1,df2],ignore_index=True)
df

   A  B
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
5  6  6

Data missing

In [61]:
df=pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
df=df.reindex(['a','b','c','d','e','f','g','h'])
df

        one       two     three
a  0.034680  0.566097  0.462549
b       NaN       NaN       NaN
c -0.815376  1.102464  1.235519
d       NaN       NaN       NaN
e -2.074797 -0.477071  1.352054
f -0.970183 -0.331989 -3.499311
g       NaN       NaN       NaN
h -0.316662  2.663024 -0.661947

In [63]:
df=pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
df=df.reindex(['a','b','c','d','e','f','g','h'])
print(df['one'].isnull())
df

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

        one       two     three
a  0.385431  0.293016  0.644034
b       NaN       NaN       NaN
c -0.440444  0.351607  2.131027
d       NaN       NaN       NaN
e -0.279732  0.373054 -0.510645
f  0.561144 -0.834648 -1.053553
g       NaN       NaN       NaN
h  1.774491 -0.248548  1.141336

Filling missing data

In [66]:
df=pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
df=df.reindex(['a','b','c','d','e','f','g','h'])
print (df)
print (df.fillna(0))

        one       two     three
a  0.334431 -2.144946 -2.077633
b       NaN       NaN       NaN
c -0.395273  0.948483  1.434666
d       NaN       NaN       NaN
e  0.418353 -0.144218 -0.604103
f -0.467366 -0.468169 -0.467044
g       NaN       NaN       NaN
h -0.367097 -1.622443  0.330013
        one       two     three
a  0.334431 -2.144946 -2.077633
b  0.000000  0.000000  0.000000
c -0.395273  0.948483  1.434666
d  0.000000  0.000000  0.000000
e  0.418353 -0.144218 -0.604103
f -0.467366 -0.468169 -0.467044
g  0.000000  0.000000  0.000000
h -0.367097 -1.622443  0.330013

In [67]:
df=pd.DataFrame({"A":[5,3,None,4],"B":[None,2,4,3],"C":[4,3,8,5],"D":[5,4,2,None]})
df

     A    B  C    D
0  5.0  NaN  4  5.0
1  3.0  2.0  3  4.0
2  NaN  4.0  8  2.0
3  4.0  3.0  5  NaN

In [68]:
df.ffill(axis=0)

     A    B  C    D
0  5.0  NaN  4  5.0
1  3.0  2.0  3  4.0
2  3.0  4.0  8  2.0
3  4.0  3.0  5  2.0

In [69]:
df=pd.DataFrame({"A":[5,3,None,4],"B":[None,2,4,3],"C":[4,3,8,5],"D":[5,4,2,None]})
df

     A    B  C    D
0  5.0  NaN  4  5.0
1  3.0  2.0  3  4.0
2  NaN  4.0  8  2.0
3  4.0  3.0  5  NaN

In [70]:
df.ffill(axis=1)

     A    B    C    D
0  5.0  5.0  4.0  5.0
1  3.0  2.0  3.0  4.0
2  NaN  4.0  8.0  2.0
3  4.0  3.0  5.0  5.0

In [71]:
df.bfill(axis='rows')

     A    B  C    D
0  5.0  2.0  4  5.0
1  3.0  2.0  3  4.0
2  4.0  4.0  8  2.0
3  4.0  3.0  5  NaN

In [74]:
df=pd.DataFrame({"A":[5,3,None,4],"B":[None,2,4,3],"C":[4,3,8,5],"D":[5,4,2,None]})
df.bfill(axis='columns')

     A    B    C    D
0  5.0  4.0  4.0  5.0
1  3.0  2.0  3.0  4.0
2  4.0  4.0  8.0  2.0
3  4.0  3.0  5.0  NaN