<a href="https://colab.research.google.com/github/Skyy777/DAVIS/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas

In [1]:
import pandas as pd
import numpy as np

In [3]:
data=np.array(['g','e','e','k','s','f','o','r','g','e','k','s'])
ser=pd.Series(data)
print(ser)

0     g
1     e
2     e
3     k
4     s
5     f
6     o
7     r
8     g
9     e
10    k
11    s
dtype: object

In [4]:
data=np.array(['g','e','e','k','s','f','o','r','g','e','k','s'])
ser=pd.Series(data)
print(ser[:5])

0    g
1    e
2    e
3    k
4    s
dtype: object

In [5]:
data=np.array(['g','e','e','k','s','f','o','r','g','e','k','s'])
ser=pd.Series(data)
print(ser[5:])

5     f
6     o
7     r
8     g
9     e
10    k
11    s
dtype: object

Binary Operation on Series

In [6]:
data=pd.Series([5,2,3,7],index=['a','b','c','d'])
data1=pd.Series([1,6,4,9],index=['a','b','d','e'])
print(data,data1)

a    5
b    2
c    3
d    7
dtype: int64 a    1
b    6
d    4
e    9
dtype: int64

In [7]:
data.add(data1,fill_value=0)

a     6.0
b     8.0
c     3.0
d    11.0
e     9.0
dtype: float64

In [8]:
data.sub(data1,fill_value=0)

a    4.0
b   -4.0
c    3.0
d    3.0
e   -9.0
dtype: float64

In [9]:
data.mul(data1,fill_value=0)

a     5.0
b    12.0
c     0.0
d    28.0
e     0.0
dtype: float64

In [10]:
data.div(data1,fill_value=0)

a    5.000000
b    0.333333
c         inf
d    1.750000
e    0.000000
dtype: float64

In [14]:
data.pow(data1,fill_value=0)
#exponential power

a       5.0
b      64.0
c       1.0
d    2401.0
e       0.0
dtype: float64

In [15]:
data.mod(data1,fill_value=0)

a    0.0
b    2.0
c    NaN
d    3.0
e    0.0
dtype: float64

In [19]:
companies=['Google','Microsoft','Facebook','Apple']
pd.Series(companies)

0       Google
1    Microsoft
2     Facebook
3        Apple
dtype: object

In [20]:
pd.Series(companies,index=[100,101,102,103])

100       Google
101    Microsoft
102     Facebook
103        Apple
dtype: object

In [21]:
pd.Series(companies,index=['GOOGLE','MSFT','FB','APPLE'])

GOOGLE       Google
MSFT      Microsoft
FB         Facebook
APPLE         Apple
dtype: object

In [23]:
companies={'GOOGLE':0,'MSFT':1,'FB':2,'APPLE':3}
pd.Series(companies)

GOOGLE    0
MSFT      1
FB        2
APPLE     3
dtype: int64

In [25]:
companies={
    'a':'GOOGLE',
    'b':'MSFT',
    'c':'FB',
    'd':'APPLE'
}
pd.Series(companies)

a    GOOGLE
b      MSFT
c        FB
d     APPLE
dtype: object

In [26]:
pd.Series(5,index=[100,101,102,103])

100    5
101    5
102    5
103    5
dtype: int64